/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Controllers_NativeAuth */

#ifndef _Included_Controllers_NativeAuth
#define _Included_Controllers_NativeAuth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Controllers_NativeAuth
 * Method:    authenticate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Controllers_NativeAuth_authenticate
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
