/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Model_Authenticator */

#ifndef _Included_Model_Authenticator
#define _Included_Model_Authenticator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Model_Authenticator
 * Method:    authenticate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Model_Authenticator_authenticate
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
